### ISSUE TITLE
Autoruler deployment is not created in control plane cluster

### ISSUE THREAD

**Issue by traghave123** [redhat-ztp/ztp-cluster-deploy#149]
Steps followed:
1. Deploy control plane cluster with 3 master nodes using ztp playbooks
2. Import control plane cluster into RHACM deployed in management cluster `leo`
3. Add worker node to control plane cluster

We observed that csr is not getting auto approved

```
[taurus@taurus-kvm-server rhacm]$ oc get csr
NAME        AGE     SIGNERNAME                                    REQUESTOR                                                                   CONDITION
csr-lb47b   54m     kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Pending
csr-p4r9z   8m49s   kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Pending
csr-rj8fk   24m     kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Pending
csr-rx8pg   39m     kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Pending
csr-tq7wm   69m     kubernetes.io/kube-apiserver-client-kubelet   system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Pending
```

While debugging we found that the pods are not created 

```
[taurus@taurus-kvm-server rhacm]$ oc get pods -n node-autolabeler
No resources found in node-autolabeler namespace.
```
Which we think are responsible for auto approving csr.

Could you please help here?

**Comment by traghave123** [comment]
I've tried to create the below artifacts manually, 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: autoruler
  name: autoruler
  namespace: node-autolabeler
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: autoruler
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: autoruler
    spec:
      containers:
      - image: quay.io/karmab/autosigner:latest
        imagePullPolicy: Always
        name: autosigner
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - image: quay.io/karmab/autolabeller:latest
        imagePullPolicy: Always
        name: autolabeller
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
status: {}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autoruler-sa-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autoruler-sa-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: autoruler-sa-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: node-autolabeler
```

This time it got approved automatically.

But we think these artifacts should be automatically created.
