### ISSUE TITLE
[ibm-telco] The MAC address for the master VMs to be read as input

### ISSUE THREAD

**Issue by maheshd2** [redhat-ztp/ztp-cluster-deploy#40]
To avoid duplicate mac address across multiple deployments, it is better we read the mac address as input. Currently the mac addresses are hard-coded.
```
- name: Create vm
  community.libvirt.virt:
    command: define
    xml: "{{ lookup('template', '{{ role_path }}/templates/ai-vm.xml') }}"
    autostart: yes
    uri: "{{ libvirt_uri }}"
  with_items:
    - { name: "master_1", mac: "52:54:00:55:f3:31" }
    - { name: "master_2", mac: "52:54:00:55:f3:32" }
    - { name: "master_3", mac: "52:54:00:55:f3:33" }
```
