### ISSUE TITLE
[ibm-telco] sriovnetwork policy deployment failed on ZTP provisioned cluster

### ISSUE THREAD

**Issue by maheshd2** [redhat-ztp/ztp-cluster-deploy#67]
We were trying to apply the policies/manifests from "https://github.com/shashiksingh/rhocp-castor" repo on a cluster provisioned via ZTP playbooks.

And we found one of the sriovnetwork manifest failing with below error.
```
[root@ztpdevhost 02-settings]# oc apply -k .
namespace/altiostar-4g-cu-ldc1 created
sriovnetwork.sriovnetwork.openshift.io/ldc1-vran-bh-s1c created
sriovnetwork.sriovnetwork.openshift.io/ldc1-vran-bh-s1u created
sriovnetwork.sriovnetwork.openshift.io/ldc1-vran-mgmt created
sriovnetwork.sriovnetwork.openshift.io/ldc1-vran-mh created
Error from server (no supported NIC is selected by the nicSelector in CR ldc1-sriov-netdevice-dell00): error when creating ".": admission webhook "operator-webhook.sriovnetwork.openshift.io" denied the request: no supported NIC is selected by the nicSelector in CR ldc1-sriov-netdevice-dell00
```

Adding further info observed while debugging the issue:

I see all our servers are intel x86 arch
```
[root@ztphost ai-deploy-cluster-remoteworker]# lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              40
On-line CPU(s) list: 0-39
Thread(s) per core:  2
Core(s) per socket:  10
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Gold 5215 CPU @ 2.50GHz
```

But the nodes are labelled as "amd64" 
```
- apiVersion: v1
  kind: Node
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Node","metadata":{"annotations":{},"labels":{"node-role.kubernetes.io/ran-cu-ldc1-dell00":"","ran.openshift.io/ldc1-sriov-netdevice-dell00":"","ran.openshift.io/ocpvirt":"","ran.openshift.io/sriov":"","topology.kubernetes.io/zone":"ldc1"},"name":"ztpdev-worker-0"}}
      machineconfiguration.openshift.io/currentConfig: rendered-worker-d06b32577375d56b58c1c1010b6c1a04
      machineconfiguration.openshift.io/desiredConfig: rendered-worker-27f459e71ea0f97593d33950c17d742a
      machineconfiguration.openshift.io/reason: ""
      machineconfiguration.openshift.io/state: Working
      volumes.kubernetes.io/controller-managed-attach-detach: "true"
    creationTimestamp: "2021-03-02T06:43:43Z"
    labels:
      beta.kubernetes.io/arch: amd64
      beta.kubernetes.io/os: linux
      kubernetes.io/arch: amd64
      kubernetes.io/hostname: ztpdev-worker-0
      kubernetes.io/os: linux
      node-role.kubernetes.io/ran-cu-ldc1-dell00: ""
      node-role.kubernetes.io/worker: ""
      node.openshift.io/os_id: rhcos
      ran.openshift.io/ldc1-sriov-netdevice-dell00: ""
      ran.openshift.io/ocpvirt: ""
      ran.openshift.io/sriov: ""
      topology.kubernetes.io/zone: ldc1
```

**Comment by maheshd2** [comment]
@dcain response in the slack channel

the nodes are labeled with amd64 because kubernetes is written in Go, amd64 is the name given for the architecture it is compiled on: https://golang.org/doc/asm#amd64.

the error message you are receiving is also indicative of the SRIOV-operator not supporting the NIC that is in your particular server.  supported NICs can be found here: https://docs.openshift.com/container-platform/4.6/networking/hardware_networks/about-sriov.html#supported-devices_about-sriov

This is our Intel Card:

![image](https://user-images.githubusercontent.com/27758674/110055550-2df2b280-7d83-11eb-9bb0-ee8fdc199bf0.png)

And I also see the NIC is capable of providing SRIOV feature and device identifier SFP28. But I do not see the vendor id anywhere.

![image](https://user-images.githubusercontent.com/27758674/110055582-406cec00-7d83-11eb-9870-9b3c72d87924.png)


After checking these features I thought card supports SRIOV. But It looks like OCP is not supporting SRIOV on this card even though card is capable.

**Comment by maheshd2** [comment]
### Another Lab Environment with latest ZTP code (And we have mellanox card here):

I see cluster got created and worker node added to the cluster
```
[root@ztphost ai-deploy-cluster-remoteworker]# aicli list cluster
+----------+--------------------------------------+--------------+---------------------+
| Cluster  |                  Id                  |    Status    |      Dns Domain     |
+----------+--------------------------------------+--------------+---------------------+
|   ztp    | 4b426de4-c938-41d1-bcfc-3942e987a101 |  installed   | rtp.raleigh.ibm.com |
| ztp-day2 | d94ee261-6077-47f3-883b-e3ad73c5d5de | adding-hosts |         N/A         |
+----------+--------------------------------------+--------------+---------------------+
[root@ztphost ai-deploy-cluster-remoteworker]# aicli list hosts
+--------------+----------+--------------------------------------+---------------------------+--------+-------------+
|     Host     | Cluster  |                  Id                  |           Status          |  Role  |      Ip     |
+--------------+----------+--------------------------------------+---------------------------+--------+-------------+
| ztp-master-1 |   ztp    | 573e503a-54d9-47f4-9b0a-cf390fde1167 |         installed         | master | 9.42.98.153 |
| ztp-master-2 |   ztp    | 384a9765-8c32-4067-bcc6-2f4cec5ae571 |         installed         | master | 9.42.98.154 |
| ztp-master-3 |   ztp    | 24433856-88ba-4150-b8bf-f0264b031346 |         installed         | master | 9.42.98.155 |
| ztp-worker-0 | ztp-day2 | 863cd849-13a7-0574-a85a-c54f0ee35f01 | added-to-existing-cluster | worker |     N/A     |
+--------------+----------+--------------------------------------+---------------------------+--------+-------------+
```

Approved the certificates:
```
[root@ztphost ai-deploy-cluster-remoteworker]#  oc get csr -o name | xargs oc adm certificate approve
certificatesigningrequest.certificates.k8s.io/csr-5kdjk approved
certificatesigningrequest.certificates.k8s.io/csr-8w7h6 approved
certificatesigningrequest.certificates.k8s.io/csr-fxvft approved
certificatesigningrequest.certificates.k8s.io/csr-jnc88 approved
certificatesigningrequest.certificates.k8s.io/csr-mr684 approved
certificatesigningrequest.certificates.k8s.io/csr-mxcff approved
```

But 'oc' command is not listing the worker node
```
[root@ztphost ai-deploy-cluster-remoteworker]# oc get nodes
NAME           STATUS   ROLES           AGE   VERSION
ztp-master-1   Ready    master,worker   27m   v1.19.0+f173eb4
ztp-master-2   Ready    master,worker   40m   v1.19.0+f173eb4
ztp-master-3   Ready    master,worker   40m   v1.19.0+f173eb4
```

I still went ahead to apply the ran manifests and see the same error. Not sure here the error is because of unavailability of worker node.
```
Warning: oc apply should be used on resource created by either oc create --save-config or oc apply
sriovnetwork.sriovnetwork.openshift.io/ldc1-vran-mh configured
Error from server (no supported NIC is selected by the nicSelector in CR ldc1-sriov-netdevice-dell00): error when creating ".": admission webhook "operator-webhook.sriovnetwork.openshift.io" denied the request: no supported NIC is selected by the nicSelector in CR ldc1-sriov-netdevice-dell00
```

SRIOV manifest:
```
[root@ztphost 02-settings]# cat 00-ldc1-sriov-node-policy.yaml
---
###############################################################################
# specific resourceName for it (eg. sriov-netdevice-dell00)
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: ldc1-sriov-netdevice-dell00
  namespace: openshift-sriov-network-operator
spec:
  resourceName: vran_netdevice
  nodeSelector:
    ran.openshift.io/sriov: ""
    ran.openshift.io/ldc1-sriov-netdevice-dell00: ""
  deviceType: netdevice
  #deviceType: vfio-pci
  priority: 10
  mtu: 1500
  numVfs: 8
  nicSelector:
    vendor: "15b3"
    deviceID: "1015"
    pfNames:
      - ens2f0#0-7
      - ens2f1#0-7
```


Node Status:
```
[root@ztphost 02-settings]# oc get nodes
NAME           STATUS     ROLES                AGE     VERSION
ztp-master-1   Ready      master,worker        37m     v1.19.0+f173eb4
ztp-master-2   Ready      master,worker        51m     v1.19.0+f173eb4
ztp-master-3   Ready      master,worker        51m     v1.19.0+f173eb4
ztp-worker-0   NotReady   ran-cu-ldc1-dell00   5m26s


[root@ztphost 02-settings]# oc describe node ztp-worker-0
Name:               ztp-worker-0
Roles:              ran-cu-ldc1-dell00
Labels:             node-role.kubernetes.io/ran-cu-ldc1-dell00=
                    ran.openshift.io/ldc1-sriov-netdevice-dell00=
                    ran.openshift.io/ocpvirt=
                    ran.openshift.io/sriov=
                    topology.kubernetes.io/zone=ldc1
Annotations:        <none>
CreationTimestamp:  Thu, 04 Mar 2021 22:26:33 -0500
Taints:             node.kubernetes.io/unreachable:NoExecute
                    node.kubernetes.io/unreachable:NoSchedule
Unschedulable:      false
Lease:              Failed to get lease: leases.coordination.k8s.io "ztp-worker-0" not found
Conditions:
  Type             Status    LastHeartbeatTime                 LastTransitionTime                Reason                   Message
  ----             ------    -----------------                 ------------------                ------                   -------
  Ready            Unknown   Thu, 04 Mar 2021 22:26:33 -0500   Thu, 04 Mar 2021 22:27:33 -0500   NodeStatusNeverUpdated   Kubelet never posted node status.
  MemoryPressure   Unknown   Thu, 04 Mar 2021 22:26:33 -0500   Thu, 04 Mar 2021 22:27:33 -0500   NodeStatusNeverUpdated   Kubelet never posted node status.
  DiskPressure     Unknown   Thu, 04 Mar 2021 22:26:33 -0500   Thu, 04 Mar 2021 22:27:33 -0500   NodeStatusNeverUpdated   Kubelet never posted node status.
  PIDPressure      Unknown   Thu, 04 Mar 2021 22:26:33 -0500   Thu, 04 Mar 2021 22:27:33 -0500   NodeStatusNeverUpdated   Kubelet never posted node status.
Addresses:
System Info:
  Machine ID:
  System UUID:
  Boot ID:
  Kernel Version:
  OS Image:
  Operating System:
  Architecture:
  Container Runtime Version:
  Kubelet Version:
  Kube-Proxy Version:
Non-terminated Pods:          (0 in total)
  Namespace                   Name    CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
  ---------                   ----    ------------  ----------  ---------------  -------------  ---
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests  Limits
  --------           --------  ------
  cpu                0 (0%)    0 (0%)
  memory             0 (0%)    0 (0%)
  ephemeral-storage  0 (0%)    0 (0%)
Events:              <none>
```
