### ISSUE TITLE
[ibm-telco] Horizontal Scale up of worker node using ztp playbooks

### ISSUE THREAD

**Issue by pmallan** [redhat-ztp/ztp-cluster-deploy#96]
Hi @yrobla we have question on scaling up worker using ztp playbook. Is it possible and supported screnario?
- Control Plane Cluster and a worker node has been deployed using ztp play book
- Try to add another worker node to the same control plane cluster using playbook. We tried this and notice that already existing worker node gets reinstalled. The expectation is that, add new worker node to the cluster without impacting existing worker node. 
- We can deploy multiple worker nodes to the cluster during first time deployment however can not scale up later. 
- Please update us whether it has been tested and supported scenario or not.

**Comment by anujit-ibm** [comment]
We have deployed cluster with one worker node.
```
[root@vcuhost ~]# aicli list clusters
+----------+--------------------------------------+--------------+---------------------+
| Cluster  |                  Id                  |    Status    |      Dns Domain     |
+----------+--------------------------------------+--------------+---------------------+
|   vcu    | d2571b9b-6e33-4122-a274-98dd97db0563 |  installed   | rtp.raleigh.ibm.com |
| vcu-day2 | b533cfe0-63c7-4936-9039-b4d2da04a3bf | adding-hosts |         N/A         |
+----------+--------------------------------------+--------------+---------------------+
[root@vcuhost ~]# aicli list hosts
+--------------+----------+--------------------------------------+---------------------------+--------+----------------+
|     Host     | Cluster  |                  Id                  |           Status          |  Role  |       Ip       |
+--------------+----------+--------------------------------------+---------------------------+--------+----------------+
| vcu-master-0 |   vcu    | d7ece5e2-64b5-4f0a-ad62-7b0155923fdd |         installed         | master | 172.29.231.142 |
| vcu-master-1 |   vcu    | 9f8b8d9a-960b-4b17-8997-11341fede901 |         installed         | master | 172.29.231.143 |
| vcu-master-2 |   vcu    | 632b3b85-e30e-4ddb-8e6e-73784d1ea716 |         installed         | master | 172.29.231.144 |
| vcu-worker-1 | vcu-day2 | 1c907474-713e-6617-ff02-a68438e3de04 | added-to-existing-cluster | worker |      N/A       |
+--------------+----------+--------------------------------------+---------------------------+--------+----------------+
```
We are trying to add one more worker node to the existing cluster. However it tries to re-install the already installed worker node as well.
```
[root@vcuhost ~]# aicli list clusters
+----------+--------------------------------------+--------------+---------------------+
| Cluster  |                  Id                  |    Status    |      Dns Domain     |
+----------+--------------------------------------+--------------+---------------------+
|   vcu    | d2571b9b-6e33-4122-a274-98dd97db0563 |  installed   | rtp.raleigh.ibm.com |
| vcu-day2 | b533cfe0-63c7-4936-9039-b4d2da04a3bf | adding-hosts |         N/A         |
+----------+--------------------------------------+--------------+---------------------+
[root@vcuhost ~]# aicli list hosts
+--------------+----------+--------------------------------------+--------------------------------+-------------+----------------+
|     Host     | Cluster  |                  Id                  |             Status             |     Role    |       Ip       |
+--------------+----------+--------------------------------------+--------------------------------+-------------+----------------+
| vcu-master-0 |   vcu    | d7ece5e2-64b5-4f0a-ad62-7b0155923fdd |           installed            |    master   | 172.29.231.142 |
| vcu-master-1 |   vcu    | 9f8b8d9a-960b-4b17-8997-11341fede901 |           installed            |    master   | 172.29.231.143 |
| vcu-master-2 |   vcu    | 632b3b85-e30e-4ddb-8e6e-73784d1ea716 |           installed            |    master   | 172.29.231.144 |
| vcu-worker-0 | vcu-day2 | e843fa08-39ad-72b5-fefe-26b898bf6122 |             known              | auto-assign |      N/A       |
| vcu-worker-1 | vcu-day2 | 1c907474-713e-6617-ff02-a68438e3de04 | installing-pending-user-action |    worker   |      N/A       |
+--------------+----------+--------------------------------------+--------------------------------+-------------+----------------+
```

**Comment by yrobla** [comment]
You will see that in inventory/hosts.sample there is a "redeploy=False" flag. If you set it to the nodes that have already been deployed, the system will skip the provision of those.

**Comment by maheshd2** [comment]
@yrobla 

"redeploy=false" is not referenced anywhere in the playbooks... I even verified the playbooks going inside.
It looks like a simple check to be introduced, but currently missing.

```
[root@vcuhost ztp-cluster-deploy]# grep -r redeploy
ai-deploy-cluster-remoteworker/inventory/hosts.sample:worker-0.test-aut.cluster-testing name=worker_0 bmc_type=SuperMicro bmc_address=192.168.111.212 bmc_user="ADMIN" bmc_password="ADMIN" smb_host=192.168.111.1 smb_path=share ip=<host_ip> hostname=<hostname> redeploy=false profile=worker-cnf
[root@vcuhost ztp-cluster-deploy]# git branch
* master
```
```
[root@vcuhost ztp-cluster-deploy]# git checkout stable/4.7
Branch 'stable/4.7' set up to track remote branch 'stable/4.7' from 'origin'.
Switched to a new branch 'stable/4.7'
[root@vcuhost ztp-cluster-deploy]#
[root@vcuhost ztp-cluster-deploy]# grep -r redeploy
ai-deploy-cluster-remoteworker/inventory/hosts.sample:worker-0.test-aut.cluster.testing name=worker_0 bmc_type=SuperMicro bmc_address=192.168.111.212 bmc_user="ADMIN" bmc_password="ADMIN" smb_host=192.168.111.1 smb_path=share ip=<host_ip> hostname=<hostname> redeploy=false profile=worker-cnf
```

**Comment by maheshd2** [comment]
@yrobla As we found redeploy flag is not implemented in the playbooks and also we found its quite tricky to use redeploy=true/false for the worker node addition via automation. 

So, we modified the code as follows to make it work. We added this logic to unblock ourselves and test the day2 worker node addition feature. Please have a look and provide us valid solution.

`./ai-deploy-cluster-remoteworker/roles/add-remote-workers/tasks/main.yml`
```
---
- name: Enroll a worker node
  include_tasks: enroll.yaml
  with_items: "{{ groups['worker_nodes'] }}"

- name: Wait until hosts are ready in Assisted Installer
  shell: "aicli list hosts | grep {{ cluster_name }}-day2 | grep 'insufficient\\|known\\|added-to-existing-cluster' | wc -l"
  register: hosts_ready
  until: hosts_ready.stdout|int == groups['worker_nodes'] | length
  retries: 100
  delay: 30
  environment:
    AI_URL: "{{ ai_url }}"
```

`./ai-deploy-cluster-remoteworker/roles/add-remote-workers/tasks/enroll.yaml`
```
---
- name: Check if worker node already added to cluster
  shell: "aicli list hosts | grep {{ hostvars[item].name }} | grep 'added-to-existing-cluster' | wc -l"
  register: host_added
  environment:
    AI_URL: "{{ ai_url }}"

- name: Enroll a SuperMicro node
  include_role:
    name: "{{ playbook_dir }}/../common-roles/enroll-supermicro"
  vars:
    iso_name: "{{ cluster_name }}-day2.iso"
    smb_host: "{{ hostvars[item].smb_host }}"
    smb_path: "{{ hostvars[item].smb_path }}"
    bmc_address: "{{ hostvars[item].bmc_address }}"
    bmc_user: "{{ hostvars[item].bmc_user }}"
    bmc_password: "{{ hostvars[item].bmc_password }}"
  when: hostvars[item].bmc_type == "SuperMicro" and host_added.stdout|int == 0

- name: Enroll a Dell node
  include_role:
    name: "{{ playbook_dir }}/../common-roles/enroll-dell"
  vars:
    iso_name: "{{ cluster_name }}-day2.iso"
    bmc_user: "{{ hostvars[item].bmc_user }}"
    bmc_password: "{{ hostvars[item].bmc_password }}"
    bmc_address: "{{ hostvars[item].bmc_address }}"
  when: hostvars[item].bmc_type == "Dell" and host_added.stdout|int == 0
```
