### ISSUE TITLE
[ibm-telco] prepare-environment step fails with latest stable/4.7 branch

### ISSUE THREAD

**Issue by maheshd2** [redhat-ztp/ztp-cluster-deploy#97]
![image](https://user-images.githubusercontent.com/27758674/114697535-a8780000-9d3b-11eb-9c5f-aaca13e71604.png)

We saw below lines are missing from the playbook under stable/4.7 branch (Below tasks are from master branch):

`roles/prepare-environment/tasks/main.yml`
```
- name: Read json with image versions
  shell: cat "/opt/assisted-service-ztp/default_ocp_versions.json"
  register: json_content

- name: Query for the right ISO according to the version
  vars:
    jsondata: "{{ json_content.stdout | from_json }}"
    query_version: "\"{{ cluster_version }}\".rhcos_image"
  set_fact:
    rhcos_base_iso: "{{ jsondata | json_query(query_version) }}"
```
